pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        AWS_ACCOUNT_ID  = "085013191936"
        AWS_REGION      = "us-east-1"
        ECR_REGISTRY    = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/demo3"
        IMAGE           = "${ECR_REGISTRY}:latest"
    }

    stages {

        stage('Validate Changes') {
            when {
                not { changeset "**/worker/**" }
            }
            steps {
                error("No changes detected in worker/ — stopping pipeline!")
            }
        }

        stage('Build Docker Image') {
            when {
                changeset "**/worker/**"
            }
            steps {
                sh """
                    cd worker
                    docker build -t ${IMAGE} .
                """
            }
        }

        stage('Login to ECR') {
            when {
                changeset "**/worker/**"
            }
            steps {
                sh """
                    aws ecr get-login-password --region ${AWS_REGION} \
                    | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                """
            }
        }

        stage('Push Image to ECR') {
            when {
                changeset "**/worker/**"
            }
            steps {
                sh "docker push ${IMAGE}"
            }
        }
    }

    post {
        always {
            echo "Pipeline completed."
        }
    }
}
